const studentrecords = {
    1: 'ABDUL_SAMAD',
    2: 'ANANDHAN_P',
    3: 'ARUN_DEVRB',
    4: 'ARUNACHALAM',
    5: 'ARUNKUMAR',
    6: 'BALA_GANESH',
    7: 'DAZIO',
    8: 'DEEPAN',
    9: 'DEEPTHI',
    10: 'DHANAVEL',
    11: 'DHINESH',
    12: 'DHIVYA_G',
    13: 'DHRISHYA',
    14: 'ESAKKIRAJA',
    15: 'EYEBELL',
    16: 'GAYATHRI',
    17: 'GOKUL',
    18: 'GOKULAKRISHNAN',
    19: 'tryagain',
    20: 'INFANT_ADHARSH',
    21: 'JAYASRI',
    22: 'JEYANDHAN',
    23: 'JITHIN_KRISHNA',
    24: 'KARTHIK_M',
    25: 'KARTHIKEYAN_C',
    26: 'KARUNYA',
    27: 'KATHIRAVAN',
    28: 'KAVIYARASAN',
    29: 'KRISHNA_VENI',
    30: 'tryagain',
    31: 'MANIKANDAN',
    32: 'MANOJKUMAR',
    33: 'MATHAN_KUMAR',
    34: 'MEGHA_BALAKRISHNAN',
    35: 'MIGAVEL',
    36: 'MITHUN',
    37: 'MOHAMMED_ANES',
    38: 'MOHANA_PRIYA',
    39: 'MUGES_KARTHIGEYAN',
    40: 'NAVEENKUMAR',
    41: 'NISHARANI',
    42: 'PAVITHRA',
    43: 'RAMYA',
    44: 'REENA',
    45: 'RIYAZAHAMED',
    46: 'SAKTHIVEL',
    47: 'SANOOP',
    48: 'SANTHIYA',
    49: 'SANTHOSHGANDHI',
    50: 'SENBAHA',
    51: 'SETHU_PATHI',
    52: 'SHAH_MAKZOOM',
    53: 'SHALINI',
    54: 'SIVABALAN',
    55: 'SRIRAM',
    56: 'STEPHEN_ADITHYA',
    57: 'SUGANTHAN',
    58: 'SUNITHA_NANDHINI',
    59: 'SURUTHY_v',
    60: 'SURYA',
    61: 'SWETHA',
    62: 'VINOTH_KRISHNAN',
    63: 'YOKESH_SARAVANAN'
}

const func1 = document.getElementById('btn1');

func1.onclick = () => {
    const rand = Math.floor(Math.random() * 63)
    console.log('the random value is', rand)
    console.log('the student is ', studentrecords[rand])
    document.getElementById('fname').value = `choosen 🤵  is rollnumber ${rand} which is ${studentrecords[rand]} `;
}